# Import Liabraries

In [1]:
import pandas as pd
import pickle

from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

# Create Training Data

In [2]:
data = {
    "mood":[
        "happy","happy",
        "sad","sad",
        "angry","angry",
        "bored","bored",
        "relaxed","relaxed"
    ],
    
    "genre":[
        "sports","adventure",
        "simulation","story-rich",
        "shooter","action",
        "puzzle","arcade",
        "casual","simulation"
    ]
}

df = pd.DataFrame(data)

df

      mood       genre
0    happy      sports
1    happy   adventure
2      sad  simulation
3      sad  story-rich
4    angry     shooter
5    angry      action
6    bored      puzzle
7    bored      arcade
8  relaxed      casual
9  relaxed  simulation

# Encode Text

In [3]:
mood_encoder = LabelEncoder()
genre_encoder = LabelEncoder()

df["mood_encoded"] = mood_encoder.fit_transform(df["mood"])
df["genre_encoded"] = genre_encoder.fit_transform(df["genre"])

df

      mood       genre  mood_encoded  genre_encoded
0    happy      sports             2              7
1    happy   adventure             2              1
2      sad  simulation             4              6
3      sad  story-rich             4              8
4    angry     shooter             0              5
5    angry      action             0              0
6    bored      puzzle             1              4
7    bored      arcade             1              2
8  relaxed      casual             3              3
9  relaxed  simulation             3              6

# Prepare Training Data

In [4]:
X = df[["mood_encoded"]]
y = df["genre_encoded"]

# Train Model

In [5]:
model = DecisionTreeClassifier()

model.fit(X,y)

print("Model trained successfully")

Model trained successfully

# Save Model

In [8]:
pickle.dump(model, open(r"C:\Users\aryan\practice projects\MoodPlay Ai\models\mood_model.pkl", "wb"))
pickle.dump(mood_encoder, open(r"C:\Users\aryan\practice projects\MoodPlay Ai\models\mood_encoder.pkl", "wb"))
pickle.dump(genre_encoder, open(r"C:\Users\aryan\practice projects\MoodPlay Ai\models\genre_encoder.pkl", "wb"))

print("Model saved successfully")

Model saved successfully